ledge/account/models.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-

import uuid
import hashlib
import datetime

from sqlalchemy.ext.hybrid import hybrid_property

from ledge.extensions import db
from ledge.corelib.mixins.jsonize import Jsonizable
from ledge.account.mixins import LowerIdMixin


current_datetime = lambda: datetime.datetime.utcnow()


# ---------
# User Role
# ---------

class UserRole(db.Model):
    """The middle table for users having roles."""

    user_id = db.Column(db.ForeignKey("user.id"), primary_key=True)
    role_id = db.Column(db.ForeignKey("role.id"), primary_key=True)
    created = db.Column(db.DateTime, nullable=False, default=current_datetime)


class RoleClosure(db.Model):
    """The role's inheritance relationship to itself."""

    parent_id = db.Column(db.ForeignKey("role.id"), primary_key=True)
    child_id = db.Column(db.ForeignKey("role.id"), primary_key=True)


class RoleQuery(db.Query):
    """Query Handler for `Role` model."""

    def create(self, role_id, parents=[], screen_name=None):
        role = Role(id=role_id, parents=list(parents),
                screen_name=screen_name)
        db.session.add(role)
        return role

    def __call__(self, role_id, *args, **kwargs):
        return self.get(role_id) or self.create(role_id, *args, **kwargs)


class Role(LowerIdMixin, db.Model):
    """The role of the user."""

    query_class = RoleQuery
    primary_key = db.Column("id", db.String(20), primary_key=True)
    parents = db.relationship("Role", secondary=RoleClosure.__table__,
            primaryjoin=(RoleClosure.child_id == primary_key),
            secondaryjoin=(RoleClosure.parent_id == primary_key))
    screen_name = db.Column(db.Unicode(20))

    def __unicode__(self):
        return self.screen_name or self.id

    def __eq__(self, other):
        return hasattr(other, "id") and self.id == other.id

    def __hash__(self):
        return hash(self.id)


# ------------
# User Account
# ------------

class UserQuery(db.Query):
    """Query Handler of `User` model."""

    def authenticate(self, email_or_username, password):
        """Authenicate by email/username and password.

        If email/username isn't exist or password is wrong, this method would
        return `None`, otherwise return the `models.User` model.
        """
        condition = ((User.email == email_or_username) |
                     (User.id == email_or_username))
        user = self.filter(condition).first()
        if not user:
            raise UserNotFoundError
        if not user.check_password(password):
            raise PasswordWrongError
        return user


class User(Jsonizable, LowerIdMixin, db.Model):
    """The account of the user."""

    query_class = UserQuery
    JSONIZE_ATTRS = ("id", "nickname", "gender", "created")
    GENDER_ENUM = ("male", "female", "unknown")

    primary_key = db.Column("id", db.String(20), primary_key=True)
    email = db.Column(db.String(64), unique=True, nullable=False)
    nickname = db.Column(db.Unicode(20))
    gender = db.Column(db.Enum(name="gender", *GENDER_ENUM), nullable=False)
    salt = db.Column(db.String(32), nullable=False)
    hashed_password = db.Column(db.String(64), nullable=False)
    created = db.Column(db.DateTime, nullable=False, default=current_datetime)
    roles = db.relationship(Role, secondary=UserRole.__table__)

    def __init__(self, **data):
        password = data.pop("password", "")
        super(User, self).__init__(**data)
        self.change_password(password)
        self.nickname = self.nickname or self.id

    def __repr__(self):
        return "<User %s(%s)>" % (self.id, self.email)

    def change_password(self, password):
        """Change a new password."""
        self.salt = uuid.uuid4().hex
        self.hashed_password = self._hash_password(self.salt, password)

    def check_password(self, input_password):
        """Check the input password is right or wrong."""
        input_password = self._hash_password(self.salt, input_password)
        return input_password == self.hashed_password

    password = hybrid_property(lambda self: None, change_password)

    @staticmethod
    def _hash_password(salt, password):
        """Calculate the hashed value of password."""
        hashed = hashlib.sha256()
        hashed.update("<%s|%s>" % (salt, password))
        return hashed.hexdigest()


class ActiveToken(db.Model):
    """The active token of new account."""

    user_id = db.Column(db.ForeignKey(User.id), primary_key=True)
    user = db.relationship(User, lazy="joined", uselist=False,
            backref=db.backref("active_token", lazy="select", uselist=False))
    value = db.Column(db.String(32), nullable=False,
            default=lambda: uuid.uuid4().hex)


# ----------
# Exceptions
# ----------

class UserNotFoundError(Exception):
    pass


class PasswordWrongError(Exception):
    pass

ledge/account/forms.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-

from flask.ext.wtf import TextField, PasswordField, RadioField, SubmitField
from flask.ext.wtf import required, email
from flask.ext.wtf.html5 import EmailField
from flask.ext.babel import lazy_gettext as _

from ledge.corelib.forms import Form, unique
from ledge.account.models import User


class SignUpForm(Form):
    """The form for signing up."""

    GENDER_CHOICES = [
            ("unknown", _(u"Private")),
            ("male", _(u"Male")),
            ("female", _(u"Female"))]

    id = TextField(_("User Name"), [required(), unique(User, User.id)])
    email = EmailField(_("Email"), [required(), email(),
            unique(User, User.email)])
    password = PasswordField(_("Password"), [required()])
    gender = RadioField(_("Gender"), [required()],
            choices=GENDER_CHOICES, default="unknown")
    nickname = TextField(_("Screen Name"), [])
    submit = SubmitField(_("Sign Up"))


class LoginForm(Form):
    """The form for login."""

    login = TextField(_("User Name or Email"), [required()])
    password = PasswordField(_("Password"), [required()])
    submit = SubmitField(_("Login"))

ledge/account/__init__.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-

from flask import Blueprint


__all__ = ("app", "views", "models", "services", "forms", "db", "context")

app = Blueprint("account", __name__, template_folder="templates",
        static_folder="static", url_prefix="/account")

ledge/account/views.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-

from flask import render_template, redirect, url_for, request, flash
from flask.ext.babel import gettext as _

from ledge.corelib.views import as_view, MethodView
from ledge.account import app
from ledge.account.models import User, UserNotFoundError, PasswordWrongError
from ledge.account.services import (SignUpService, TokenUsedError,
        TokenWrongError)
from ledge.account.forms import SignUpForm, LoginForm
from ledge.account.context import session_login, session_logout, authenticated


# -------------
# Sign Up Views
# -------------

@app.route("/signup")
@as_view(name="signup")
class SignUpView(MethodView):
    """The view to sign up."""

    def prepare(self):
        self.form = SignUpForm()
        self.user = User()
        self.service = SignUpService(self.user)

    def get(self):
        return render_template("signup.html", **vars(self))

    def post(self):
        #: validate input
        if not self.form.validate():
            return render_template("signup.html", **vars(self))
        #: inject data
        self.form.populate_obj(self.user)
        #: call the sign up service
        self.service.signup()
        self.service.send_confirm_mail()
        #: redirect to user's person page
        return redirect(url_for("account.person", id=self.user.id))


@app.route("/<string:id>/confirm")
def confirm(id):
    """The view to confirm a new account's email."""
    #: get resources
    user = User.query.get_or_404(id)
    service = SignUpService(user)
    input_token = request.args['token']

    #: active current account
    try:
        service.active(input_token)
    except TokenUsedError:
        message = _(u"The account had been actived.")
        return render_template("confirm-failed.html", message=message), 403
    except TokenWrongError:
        message = _(u"The active token is invalid.")
        return render_template("confirm-failed.html", message=message), 403

    #: automatic sign in
    session_login(user)
    #: output a success message
    message = _(u"The account has been actived successfully.")
    return render_template("confirm-success.html", message=message)


# -----------
# Login Views
# -----------

@app.route("/login")
@as_view(name="login")
class LoginView(MethodView):
    """The view to login."""

    def prepare(self):
        self.form = LoginForm()

    def _render_page(self):
        return render_template("login.html", **vars(self))

    def get(self):
        return self._render_page()

    def post(self):
        #: validate input
        if not self.form.validate():
            return self._render_page()

        #: try to authenticate
        try:
            user = User.query.authenticate(self.form.login.data,
                    self.form.password.data)
        except (UserNotFoundError, PasswordWrongError):
            message = _(u"The user is not found or the password is wrong.")
            flash(message, "error")
            return self._render_page()
        else:
            session_login(user)
            flash(_(u"Welcome %(name)s.", name=user.nickname), "info")

        #: redirect to user's person page
        return redirect(url_for("master.home"))


@app.route("/logout")
@authenticated
def logout():
    session_logout()
    return redirect(url_for("master.home"))


@app.route("/<string:id>")
def person(id):
    user = User.query.get_or_404(id)
    return render_template("person.html", user=user)

ledge/account/templates/confirm-email.html
{%- set url = url_for("account.confirm", id=user.id, token=user.active_token.value, _external=True) -%}

{%- macro link() -%}
    <a href="{{ url }}">{{ _("this link") }}</a>
{%- endmacro -%}

<p>{{ _("Welcome to join ledge!") }}</p>
<p>{{ _("Please click %(link)s to active your account.", link=link()) | safe }}</p>
<p>{{ _("If you could not do that, please copy this URL to your browser's address bar.") }}</p>
<p>
    <pre>{{ url }}</pre>
</p>

ledge/account/templates/confirm-failed.html
{% extends "layout/master.html" %}

{% block body %}
    <h2>Failed</h2>

    <p>{{ message }}</p>
{% endblock %}

ledge/account/templates/confirm-success.html
{% extends "layout/master.html" %}

{% block body %}
    <h2>Success</h2>

    <p>{{ message }}</p>
{% endblock %}

ledge/account/templates/login.html
{% extends "layout/master.html" %}
{% import "helpers/form.html" as helper_form %}


{% block body %}
    <form action="{{ request.path }}" method="post" class="form-horizontal">
        <fieldset>
            <legend>{{ _("Login") | title }}</legend>
            {{ helper_form.render_field(form.login) }}
            {{ helper_form.render_field(form.password) }}
        </fieldset>

        <div class="form-actions">
            {{ form.csrf_token() }}
            {{ form.submit(class="btn btn-large btn-primary") }}
            <a href="{{ url_for('account.signup') }}" class="btn btn-large">{{ _('Sign Up') }}</a>
        </div>
    </form>
{% endblock %}

ledge/account/templates/person.html
{% extends "layout/master.html" %}

{% block body %}

    <h2>Home Page of {{ user.nickname }}</h2>

    <div class="well">
        <p>User ID: {{ user.id }}</p>
        <p>Screen Name: {{ user.nickname }}</p>
        <p>Gender: {{ user.gender.title() }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Roles:
            {%- for role in user.roles %}
                <span class="label">{{ role }}</span>
            {%- else %}
                Nothing
            {%- endfor %}
        </p>
    </div>

{% endblock %}

ledge/account/templates/profile.html
{% extends "layout/master.html" %}

{% block body %}

    <h2>Home Page of {{ user.nickname }}</h2>

    <div class="well">
        <p>User ID: {{ user.id }}</p>
        <p>Screen Name: {{ user.nickname }}</p>
        <p>Gender: {{ user.gender.title() }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Roles:
            {%- for role in user.roles %}
                <span class="label">{{ role }}</span>
            {%- else %}
                Nothing
            {%- endfor %}
        </p>
    </div>

{% endblock %}

ledge/account/templates/signup.html
{% extends "layout/master.html" %}
{% import "helpers/form.html" as helper_form %}


{% block body %}
    <form action="{{ request.path }}" method="post" class="form-horizontal">
        <fieldset>
            <legend>{{ _("Create a new account") | title }}</legend>
            {{ helper_form.render_field(form.id) }}
            {{ helper_form.render_field(form.email) }}
            {{ helper_form.render_field(form.password) }}
            {{ helper_form.render_radios(form.gender) }}
            {{ helper_form.render_field(form.nickname) }}
        </fieldset>

        <div class="form-actions">
            {{ form.csrf_token() }}
            {{ form.submit(class="btn btn-large btn-primary") }}
            <input type="reset" class="btn btn-large" value="{{ _('Reset') }}" />
        </div>
    </form>
{% endblock %}